spring.application.name=TestingApp

#for local host database no need to write username and password
#DB configuration
spring.datasource.url=jdbc:mysql://localhost:3306/mysqldb

spring.datasource.username=root
spring.datasource.password=digvijay@5199
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

my.variable=dev